import {
  addPositionComponent,
  addRotationComponent,
} from '@forge-game-engine/forge/common';
import { EcsWorld } from '@forge-game-engine/forge/ecs';
import { Random, Vector2 } from '@forge-game-engine/forge/math';
import {
  addPhysicsBodyComponent,
  RigidBody,
  TerrainShape,
} from '@forge-game-engine/forge/physics';
import {
  buildTerrainCurve,
  Color,
  createTerrainMesh,
  RenderContext,
  TerrainMesh,
} from '@forge-game-engine/forge/rendering';
import { getAssetUrl } from '@site/src/utils/get-asset-url';

// How far apart (in local x) the sparse control points the terrain curve is
// built from are. Small enough that the smooth curve through them still
// reads as "rolling hills that get steeper" rather than a handful of
// disconnected bumps, large enough to keep the whole `courseLength`-long
// course's control point count (and therefore its dense curve point / mesh
// vertex count) small.
const anchorSpacing = 500;

// How many curve points to sample per anchor-to-anchor segment. Both the
// TerrainShape collision points and the render mesh use this same dense
// sampling, so what the car touches always matches what's drawn.
const samplesPerSegment = 20;

const terrainDepth = 500;

/**
 * How far the flat launch pad the car spawns on extends before the terrain
 * starts climbing, in world units. Control points at or before this x are
 * held flat at height 0.
 */
const flatStartLength = 400;

/**
 * How far past `flatStartLength` the hills take to ramp up to full
 * amplitude, via a smoothstep applied to `heightAt`'s hill/climb/noise
 * terms. Without this, those terms would switch on abruptly at
 * `flatStartLength` with a nonzero slope there, kinking the curve right at
 * the edge of the launch pad instead of easing out of it smoothly.
 */
const hillRampLength = 800;

const groundColor = Color.fromHSLA(95, 45, 30);
const dirtColor = Color.fromHSLA(30, 35, 22);

/**
 * Total horizontal distance the generated course covers, including the
 * flat launch pad.
 */
const courseLength = 20000;

/**
 * How far left of `x = 0` the terrain (and its flat launch pad) extends, so
 * the car's spawn point isn't sitting right at the terrain's own left edge.
 */
const courseStart = -200;

/**
 * Computes the control-point height at `x`: flat for `flatStartLength`,
 * then a mix of two sine waves at different frequencies (rolling hills), a
 * steady upward trend (so the course is a net "climb" rather than just
 * undulating), and small per-anchor noise so it doesn't read as perfectly
 * periodic - all ramped in smoothly over `hillRampLength` so the transition
 * out of the flat pad has no sudden change in slope. Sampled sparsely (see
 * `anchorSpacing`) and smoothed into a continuous curve by
 * `buildTerrainCurve`, rather than describing the surface directly, so the
 * terrain has none of a stepped heightmap's hard edges for the car to catch
 * on.
 * @param x - The world-space x coordinate to sample.
 * @param random - The seeded random source used for per-anchor noise.
 */
function heightAt(x: number, random: Random): number {
  if (x <= flatStartLength) {
    return 0;
  }

  const distanceIntoHills = x - flatStartLength;

  const rollingHills =
    Math.sin(distanceIntoHills * 0.0012) * 140 +
    Math.sin(distanceIntoHills * 0.0035 + 1.7) * 60;
  const climb = distanceIntoHills * 0.045;
  const noise = random.randomFloat(-12, 12);

  const rampT = Math.min(distanceIntoHills / hillRampLength, 1);
  const ramp = rampT * rampT * (3 - 2 * rampT);

  return (rollingHills + climb + noise) * ramp;
}

/**
 * Builds the course's control points in local space, given the terrain
 * body's required 180 degree rotation (see `createTerrain`): that rotation
 * negates both axes, so a point authored straight from `heightAt` at
 * world-space `x` - i.e. `Vector2(x, heightAt(x))` - would land at world
 * `(-x, -heightAt(x))` once rotated, climbing "backwards" (towards
 * decreasing world x) from a spawn point sitting right at the terrain's
 * world-space edge instead of comfortably inside it. Negating both
 * coordinates here undoes that in advance, so rotating each resulting local
 * point by `Math.PI` maps it straight back to `(x, heightAt(x))` in world
 * space - matching `heightAt`'s own x parameter and sign exactly, and letting
 * `createTerrain`'s `spawnPosition` be authored directly in the same
 * straightforward world coordinates.
 *
 * `TerrainShape`/`buildTerrainCurve` both require points ordered by
 * strictly increasing local x; since negating `x` reverses that order,
 * points are generated by increasing world-space `x` first and reversed
 * afterwards.
 * @param random - The seeded random source used for per-anchor noise.
 */
function buildControlPoints(random: Random): Vector2[] {
  const worldPoints: Vector2[] = [];

  for (let x = courseStart; x < courseLength; x += anchorSpacing) {
    worldPoints.push(new Vector2(x, heightAt(x, random)));
  }

  worldPoints.push(new Vector2(courseLength, heightAt(courseLength, random)));

  return worldPoints
    .reverse()
    .map((point) => new Vector2(-point.x, -point.y));
}

export interface HillClimbTerrain {
  /** The terrain's static `RigidBody`, for reference. */
  body: RigidBody;

  /** A point on the flat launch pad the car should spawn above. */
  spawnPosition: Vector2;

  /** The terrain's render mesh, for `createTerrainRenderEcsSystem`. */
  mesh: TerrainMesh;
}

/**
 * Builds the course's terrain: a single `TerrainShape` ground body following
 * a smooth curve through a procedurally generated height profile (see
 * `heightAt`), starting with a flat launch pad and climbing into
 * increasingly steep rolling hills, plus a matching render mesh (see
 * `createTerrainMesh`) textured with a tileable grass-like border blending
 * into a tileable dirt-like fill. Pair with `createTerrainRenderEcsSystem`
 * to draw the returned `mesh`.
 * @param world - The ECS world to add the terrain entity to.
 * @param renderContext - The render context used to load the terrain's textures and build its mesh.
 * @param random - The seeded random source used to vary the terrain.
 */
export async function createTerrain(
  world: EcsWorld,
  renderContext: RenderContext,
  random: Random,
): Promise<HillClimbTerrain> {
  const controlPoints = buildControlPoints(random);
  const curvePoints = buildTerrainCurve(controlPoints, samplesPerSegment);
  const points = curvePoints.map((curvePoint) => curvePoint.position);

  const terrainShape = new TerrainShape(points, terrainDepth);

  // Rotated 180 degrees: `TerrainShape` always extends its solid slab
  // `depth` units in the +y direction from its surface points (in its own
  // local space), but this demo's gravity pulls bodies toward -y, so the
  // body is flipped to face the right way (see the Rolling Ball demo, which
  // does the same).
  const angle = Math.PI;
  const position = Vector2.zero;

  const terrainBody = new RigidBody({
    shape: terrainShape,
    position,
    angle,
    isStatic: true,
    friction: 1,
  });

  const terrainEntity = world.createEntity();

  addPositionComponent(world, terrainEntity, {
    world: position.clone(),
    local: position.clone(),
  });

  // `RotationEcsComponent.world` is negated relative to `RigidBody.angle`
  // (see the "Coordinate spaces" note in the Bodies and Shapes guide), the
  // same convention `createPhysicsSyncEcsSystem` uses for every other
  // static body.
  addRotationComponent(world, terrainEntity, {
    local: -angle,
    world: -angle,
  });

  addPhysicsBodyComponent(world, terrainEntity, {
    physicsBody: terrainBody,
  });

  const [borderImage, fillImage] = await Promise.all([
    renderContext.imageCache.getOrLoad(
      getAssetUrl('img/kenney_pattern-pack/PNG/Default/pattern_19.png'),
    ),
    renderContext.imageCache.getOrLoad(
      getAssetUrl('img/kenney_pattern-pack/PNG/Default/pattern_37.png'),
    ),
  ]);

  const mesh = createTerrainMesh(renderContext, {
    curvePoints,
    depth: terrainDepth,
    position,
    angle,
    border: {
      image: borderImage,
      tileSize: new Vector2(160, 150),
      tint: groundColor,
    },
    fill: {
      image: fillImage,
      tileSize: new Vector2(30, 30),
      tint: dirtColor,
    },
    borderWidth: 30,
    borderBlend: 10,
  });

  return {
    body: terrainBody,
    // The flat launch pad spans `courseStart` to `flatStartLength`, both
    // held at height 0 by `heightAt`, so any x in that range - here, close
    // to the pad's start so the car has room to accelerate before the climb
    // begins - is a valid, exactly-flat spawn point.
    spawnPosition: new Vector2(150, 0),
    mesh,
  };
}
