name: Create Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (semver)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.release_type }} --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Get new version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build package
        run: npm run build

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BOT_PAT }}
        run: npm publish

      - name: Commit and push release
        run: |
          git add package.json package-lock.json
          git commit -m "chore(release): v$VERSION"
          git push
          git tag $VERSION
          git push origin $VERSION
          git push origin main
